name = "nook-worker"
compatibility_date = "2025-12-16"
main = "src/index.ts"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "nook-db"
database_id = ""

[[r2_buckets]]
binding = "VIDEOS_BUCKET"
bucket_name = "nook-videos"

[[r2_buckets]]
binding = "THUMBNAILS_BUCKET"
bucket_name = "nook-thumbnails"

[placement]
mode = "smart"